spring:
  h2:
    console:
      enabled: true
  application:
     name=oauth
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test
    platform: postgres
    hikari:
        connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

logging:
   level:
      org.springframework.security: trace



